api/urls.py
from rest_framework.routers import DefaultRouter

from .views.accounts import AccountsViewSet
from .views.characters import CharactersViewSet

router = DefaultRouter()
router.register(r'accounts', AccountsViewSet, basename='accounts')
router.register(r'characters', CharactersViewSet, basename='characters')

urlpatterns = router.urls

manager/urls.py
from django.urls import path

from manager.views import (
    AccountsListView,
    AccountsCreateView,
    AccountDeleteView
)
from manager.views.character_create import CharacterCreateView

urlpatterns = [
    path('', AccountsListView.as_view(), name='home'),
    path('accounts/create', AccountsCreateView.as_view(), name='account-create'),
    path('accounts/<str:name>/characters/create', CharacterCreateView.as_view(),
         name='account-detail-character-create'),
    path('accounts/<int:pk>', AccountDeleteView.as_view(), name='account-detail-delete'),
]

manager/models/account.py
from django.core.validators import (
    MinLengthValidator,
)
from django.db import models
from django.utils import timezone

from manager.validators import alphanumeric_validator


class Account(models.Model):
    class Realm(models.TextChoices):
        EUROPE = "Europe", "Europe"
        US_WEST = "US West", "US West"
        US_EAST = "US East", "US East"
        ASIA = "Asia", "Asia"

    name = models.CharField(
        max_length=15,
        validators=[alphanumeric_validator, MinLengthValidator(2)],
        unique=True
    )
    profile = models.ForeignKey(
        'profiles.Profile', on_delete=models.CASCADE, related_name='accounts'
    )
    realm = models.CharField(max_length=7, choices=Realm.choices)
    last_visited = models.DateTimeField(default=timezone.now, null=True, blank=True)
    expired = models.BooleanField(default=False, null=True, blank=True)

    def __str__(self) -> str:
        return f"{self.name}  @{self.realm}"

    def get_all_characters(self):
        return self.chars.all()

    def get_all_characters_count(self) -> int:
        return self.chars.all().count()

    def update_last_visited(self) -> None:
        self.last_visited = timezone.now()
        self.save(update_fields=['last_visited'])

    class Meta:
        ordering = ['id']

manager/models/character.py
from datetime import timedelta

from django.core.validators import (
    MaxValueValidator,
    MinValueValidator,
)
from django.db import models
from django.utils import timezone

from manager.validators import letters_only_validator, underscore_validator


class Character(models.Model):
    class Class(models.TextChoices):
        AMAZON = 'Amazon', 'Amazon'
        BARBARIAN = 'Barbarian', 'Barbarian'
        NECROMANCER = 'Necromancer', 'Necromancer'
        PALADIN = 'Paladin', 'Paladin'
        SORCERESS = 'Sorceress', 'Sorceress'
        DRUID = 'Druid', 'Druid'
        ASSASSIN = 'Assassin', 'Assassin'

    name = models.CharField(
        max_length=15,
        validators=[letters_only_validator, underscore_validator],
        unique=True
    )
    level = models.IntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(99)]
    )
    char_class = models.CharField(choices=Class.choices, max_length=11)
    acc = models.ForeignKey('manager.Account', on_delete=models.CASCADE, related_name='chars')
    last_visited = models.DateTimeField(default=timezone.now)
    expired = models.BooleanField(default=False)
    expansion = models.BooleanField(default=True, null=True, blank=True)
    hardcore = models.BooleanField(default=False, null=True, blank=True)
    ladder = models.BooleanField(default=False, blank=True)

    def __str__(self) -> str:
        return f"{self.name}: {self.char_class} {self.level}lvl"

    def get_class_image(self) -> str | None:
        for char_choice in self.Class.choices:
            if self.char_class in char_choice:
                pic_name = str(self.char_class + ".gif").lower()
                return f"manager/images/{pic_name}"
        return None

    def update_last_visited(self) -> None:
        self.last_visited = timezone.now()
        self.save(update_fields=['last_visited'])

    def update_expired(self) -> None:
        self.expired = self.expires < 0
        self.save(update_fields=['expired'])

    @property
    def expires(self) -> int:
        expiration_date = self.last_visited + timedelta(days=90)
        days_until = expiration_date - timezone.now()
        return days_until.days

    class Meta:
        ordering = ['id']

manager/models/equipment.py
from django.db import models


class Equipment(models.Model):
    char = models.OneToOneField('manager.Character', on_delete=models.CASCADE)
    helmet = models.CharField(
        default=None, null=True, blank=True, max_length=50
    )
    armor = models.CharField(
        default=None, null=True, blank=True, max_length=50
    )
    belt = models.CharField(
        default=None, null=True, blank=True, max_length=50
    )
    gloves = models.CharField(
        default=None, null=True, blank=True, max_length=50
    )
    boots = models.CharField(
        default=None, null=True, blank=True, max_length=50
    )
    amulet = models.CharField(
        default=None, null=True, blank=True, max_length=50
    )
    left_ring = models.CharField(
        default=None, null=True, blank=True, max_length=50
    )
    right_ring = models.CharField(
        default=None, null=True, blank=True, max_length=50
    )
    main_hand = models.CharField(
        default=None, null=True, blank=True, max_length=50
    )
    off_hand = models.CharField(
        default=None, null=True, blank=True, max_length=50
    )
    switch_main_hand = models.CharField(
        default=None, null=True, blank=True, max_length=50
    )
    switch_off_hand = models.CharField(
        default=None, null=True, blank=True, max_length=50
    )
    torch = models.CharField(
        default=None, null=True, blank=True, max_length=10
    )
    anni = models.CharField(
        default=None, null=True, blank=True, max_length=10
    )
    charms = models.CharField(
        default=None, null=True, blank=True, max_length=100
    )

    def __str__(self) -> str:
        return f"{self.char.name}'s equipment"

manager/forms/account.py
from django import forms

from manager.models import Account


class CreateAccountForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = (
            'name', 'realm'
        )

manager/forms/character.py
from django import forms
from django.forms.widgets import CheckboxInput

from manager.models import Character


class CreateCharacterForm(forms.ModelForm):
    level = forms.IntegerField(min_value=1, max_value=99)

    class Meta:
        model = Character
        fields = ['name', 'char_class', 'level', 'expansion', 'hardcore', 'ladder']
        widgets = {
            "ladder": CheckboxInput(attrs={'checked': False}),
            "expansion": CheckboxInput(attrs={'checked': True}),
            "hardcore": CheckboxInput(attrs={'checked': False})
        }

manager/views/account_create.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.utils import timezone
from django.views import generic

from manager.forms.account import CreateAccountForm


class AccountsCreateView(LoginRequiredMixin, generic.CreateView):
    """Current user can add his accounts."""

    form_class = CreateAccountForm
    template_name = 'manager/account_create.html'

    def form_valid(self, form: CreateAccountForm) -> HttpResponseRedirect:
        form.instance.profile = self.request.user.profile
        form.instance.last_visited = timezone.now()
        return super().form_valid(form)

    def get_success_url(self) -> str:
        return reverse('home')

manager/views/account_delete.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.urls import reverse_lazy
from django.views.generic import DeleteView

from manager.models import Account


class AccountDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    """Confirm that you want to delete selected account"""

    model = Account
    success_url = reverse_lazy('home')
    template_name = 'manager/account_delete.html'

    def test_func(self) -> bool:
        """Checks if current user is the creator of this account."""

        account = self.get_object()
        user = self.request.user
        return user.profile.accounts.contains(account)

manager/views/accounts_list.py
from django.db.models import QuerySet
from django.views import generic

from manager.models import Account


class AccountsListView(generic.ListView):
    """List all accounts accessible to the current user or empty page otherwise."""

    model = Account
    template_name = 'manager/index.html'
    context_object_name = 'user_accounts'

    def get_queryset(self) -> QuerySet[Account]:
        if not self.request.user.is_authenticated:
            return Account.objects.none()

        return self.request.user.profile.accounts.all()

manager/views/character_create.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import transaction
from django.db.models import QuerySet
from django.http import HttpResponseRedirect
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views import generic

from manager.forms.character import CreateCharacterForm
from manager.models import Account

MAXIMUM_CHARACTERS_PER_ACCOUNT = 18
MAXIMUM_CHARACTERS_MESSAGE = 'Reached max number of characters per account!'


class CharacterCreateView(LoginRequiredMixin, generic.CreateView):
    """Current user can add a new character to the account
    where he clicked the button to do so. User can have up to 18 characters.
    """

    model = Account
    form_class = CreateCharacterForm
    template_name = 'manager/character_create.html'
    redirect_url = reverse_lazy('home')

    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()

        if self.object is None:
            return redirect(self.redirect_url)

        return super().dispatch(request, *args, **kwargs)

    def get_queryset(self) -> QuerySet[Account]:
        return Account.objects.filter(profile__user=self.request.user)

    def get_object(self, *args, **kwargs) -> Account | None:
        queryset = self.get_queryset()
        return queryset.filter(name=self.kwargs['name']).first()

    @transaction.atomic
    def form_valid(self, form: CreateCharacterForm) -> HttpResponseRedirect:
        account = self.get_object()

        if account.get_all_characters_count() >= MAXIMUM_CHARACTERS_PER_ACCOUNT:
            messages.warning(self.request, MAXIMUM_CHARACTERS_MESSAGE)
            return redirect('home')

        instance = form.save(commit=False)
        instance.acc = account

        account.update_last_visited()

        instance.save()
        return redirect(self.get_success_url())

    def get_success_url(self) -> str:
        return self.redirect_url

manager/templates/manager/account_create.html
{% extends 'manager/base.html' %} {% block main %}
  <div class="content-section create-acc">
    <form action="" method="POST">
      {% csrf_token %} {{ form.as_p }}
      <div class="create-acc-buttons">
        <button class="btn-char"><a href="{% url 'home' %}">Exit</a></button>
        <button class="btn-char" type="submit">Ok</button>
      </div>
    </form>
  </div>
{% endblock main %}
{% block additional_js %}{% endblock additional_js %}

manager/templates/manager/account_delete.html
{% extends 'manager/base.html' %}

{% block main %}
  <div class="container container-main mt-5">
    <form method="POST">
      {% csrf_token %}
      <fieldset class="form-group">
        <legend class="border-bottom mb-4">Delete Account: {{ object.name }}</legend>
        <h2>Are you sure you want to delete this account?
          All the saved characters will be lost!</h2>
      </fieldset>
      <div class="form-group">
        <button class="btn btn-outline-danger" type="submit">YES</button>
        <a class="btn btn-outline-secondary" href="{% url 'home' %}">NO</a>
      </div>
    </form>
  </div>
{% endblock main %}

{% block additional_js %}
{% endblock additional_js %}

manager/templates/manager/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <!-- Bootstrap -->
  <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
      integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z"
      crossorigin="anonymous"
  />
  <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css"
  />
  <!-- CSS -->
  {% block css_links %}
    <link rel="stylesheet" href="{% static 'manager/css/style.css' %}"/>
  {% endblock css_links %} {% block css_chars %}
  <link rel="stylesheet" href="{% static 'manager/css/createChar.css' %}"/>
{% endblock css_chars %}
  <!-- Favicon -->
  <link rel="icon" href="{% static 'manager/images/diablo.ico' %}"/>
  <title>DoNotExpire</title>
</head>

<body>
{% block nav_img %}
  <nav class="navbar navbar-expand-lg container container-main">
    <a class="navbar-brand mr-auto ml-auto" href="{% url 'home' %}"
    ><img src="{% static 'manager/images/diablo_logo.gif' %}"
    /></a>
  </nav>
{% endblock nav_img %}

<div class="container">{% block main %} {% endblock main %}</div>
<!-- JQuery -->
<script
    src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"
></script>
<script
    src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
    crossorigin="anonymous"
></script>
<script
    src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
    crossorigin="anonymous"
></script>

{% block additional_js %}
  <script
      type="text/javascript"
      src="{% static 'manager/js/index.js' %}"
  ></script>
{% endblock additional_js %}
</body>
</html>

manager/templates/manager/character_create.html
{% extends 'manager/base.html' %}

{% load static %}

{% block css_links %}
{% endblock css_links %}

{% block nav_img %}
{% endblock nav_img %}


{% block main %}
  <h1 class="title-select">SELECT HERO CLASS</h1>

  <div>
    <h1 class="title-class" id="class-name">CLASSNAME</h1>
    <p class="class-description" id="class-description">DESCRIPTION OF A CLASS</p>
  </div>

  {% if messages %}
    {% for message in messages %}
      <div class="alert alert-{{ message.tags }}">
        {{ message }}
      </div>
    {% endfor %}
  {% endif %}

  <div class="row">
    <div class="col">
      <img src="{% static 'manager/images/create_amazon.gif' %}" class="img-fluid" id="amazon" alt="">
    </div>

    <div class="col">
      <img src="{% static 'manager/images/create_assassin.gif' %}" class="img-fluid img-assassin" id="assassin" alt="">
    </div>

    <div class="col">
      <img src="{% static 'manager/images/create_necromancer.gif' %}" class="img-fluid" id="necromancer" alt="">
    </div>

    <div class="col">
      <img src="{% static 'manager/images/create_barbarian.gif' %}" class="img-fluid" id="barbarian" alt="">
    </div>

    <div class="col">
      <img src="{% static 'manager/images/create_paladin.gif' %}" class="img-fluid" id="paladin" alt="">
    </div>

    <div class="col">
      <img src="{% static 'manager/images/create_sorceress.gif' %}" class="img-fluid" id="sorceress" alt="">
    </div>

    <div class="col">
      <img src="{% static 'manager/images/create_druid.gif' %}" class="img-fluid" id="druid" alt="">
    </div>
  </div>

  <div class="fireplace">
    <img src="{% static 'manager/images/fireplace.gif' %}" alt="">
  </div>

  <form action="" method="POST">
    <div class="char-form">
      <div id="char-form-popup">
        {% csrf_token %}
        <h6>CHARACTER NAME</h6>
        {{ form.name }}
        {{ form.level }}<br>
        {{ form.char_class }}
        {{ form.ladder }}<label for="id_ladder">Ladder Character</label><br>
        {{ form.expansion }}<label for="id_expansion">EXPANSION CHARACTER</label><br>
        {{ form.hardcore }}<label for="id_hardcore">HARDCORE</label><br>
      </div>
    </div>

    <div class="buttons">
      <button class="btn-left btn-char">
        <a href="{% url 'home' %}">EXIT</a>
      </button>

      <button class="btn-right btn-char" type="submit">
        OK
      </button>
    </div>
  </form>

  <script type="text/javascript" src={% static 'manager/js/createChar.js' %}></script>
{% endblock main %}